### ISSUE TITLE
Use different form input 

### ISSUE THREAD

**Issue by luis-aparicio** [EdutainmentLIVE/gaston#2]
On Android (maybe IOS too) I cant actually see the dial to move the 'Count' field up or down. This element messes with the field accepting manual input (which is all you can do since you cant actually 'spin' it).

**Comment by tfausak** [comment]
I thought it was a number input?

https://github.com/EdutainmentLIVE/gaston/blob/5da946e104785bf7805556e34d6d026d3e686688/source/Gaston/View.elm#L58

**Comment by luis-aparicio** [comment]
I guess the real issue here is I cannot backspace the first digit when changing the count (this element type needs some digit at all times). This results in having to refresh to app to enter a new number.

**Comment by luis-aparicio** [comment]
Perhaps we can do text input with filtering?

**Comment by tfausak** [comment]
We could add a button to clear/reset the input. 

I kind of like that it keeps the last number you entered. Makes it easy to add sets with the same number of reps all day.
