### ISSUE TITLE
Cannot Submit "bicycle-crunch" 

### ISSUE THREAD

**Issue by luis-aparicio** [EdutainmentLIVE/gaston#3]
If you open the app and immediately try to submit "bicycle-crunch" it will submit "push-ups" instead. This could possibly be due to what the default value is? This default should probably be "bicycle-crunch".

**Comment by tfausak** [comment]
I think I fixed this with https://github.com/EdutainmentLIVE/gaston/commit/06ae1598f4fc1d4e7657317dd73a9d17b4b37eac.
